### PR TITLE
Release v1.3.0

### PR DESCRIPTION
**Pull request by ElemelonWind**
## Version 1.3.0
`@yext/answers-headless-react` is now `@yext/search-headless-react`!  This means that much of the `answers` terminology is now deprecated and have been replaced by new `search` terms.
### Changes
- The following identifiers were renamed in (https://github.com/yext/search-headless-react/pull/143):
  - `AnswersHeadlessContext` &rarr; `SearchHeadlessContext`
  - `AnswersActions` &rarr; `SearchActions`
  - `AnswersUtilities` &rarr; `SearchUtilities`
  - `useAnswersActions` &rarr; `useSearchActions`
  - `useAnswersState` &rarr; `useSearchState`
  - `useAnswersUtilities` &rarr; `useSearchUtilities`
  - `AnswersHeadlessProvider` &rarr; `SearchHeadlessProvider`
- Additionally, direct exports from what was previously `@yext/answers-headless` have been replaced by their `@yext/search-headless` counterparts:
   - `answersUtilities` &rarr; `searchUtilities`
   - `provideAnswersHeadless` &rarr; `provideHeadless`
   - `AnswersHeadless` &rarr; `SearchHeadless`
   - `AnswersConfig` &rarr; `SearchConfig`
   - `AnswersConfigWithToken` &rarr; `SearchConfigWithToken`
   - `AnswersConfigWithApiKey` &rarr; `SearchConfigWithApiKey`
   - `AnswersCore` &rarr; `SearchCore`
   - `AnswersError` &rarr; `SearchError`
   - `AnswersRequest` &rarr; `SearchRequest`
   - `BaseAnswersConfig` &rarr; `BaseSearchConfig`
- Finally, `subscribeToStateUpdates` was deprecated in (https://github.com/yext/search-headless-react/pull/142)

### CODE REVIEW

**Comment by ElemelonWind** [comment]
> Can the PR description be updated to match the renaming release PRs in Core and Headless? It should probably also mention that `subscribeToStateUpdates` was deprecated

K, updated!

**Comment by ElemelonWind** [comment]
> Can the PR number be added for the `subscribeToStateUpdates` deprecation?
> 
> Also, the Core models are exported from Headless. If we're listing the changes from Headless, maybe those changes should be included as well

done :)

**Comment by ElemelonWind** [comment]
> nit: can we remove the reference to Core in the description? because technically, the exports are coming from Headless (which uses Core under the hood, but Headless-React doesn't have knowledge of that). you could change it back to what it used to be ("Additionally, direct exports from what was previously `@yext/answers-headless` have been replaced by their `@yext/search-headless` counterparts")

ah ok, got it

**Review by nmanu1 — APPROVED** [review]
Looks good! Just like for Headless, make sure to do a merge commit and to copy the PR title and description as the commit title and description :)

**Pull request merged**
