### PR TITLE
Version 2.0.0

### PR DESCRIPTION
**Pull request by yen-tt**
### Breaking Changes
- Upgraded search-headless dependency to V2. This means re-exported interfaces related to static filters and direct answers stems from search-headless V1 have been changed or removed in headless-react V2.
  - for more details, see the breaking changes listed in V2 [release notes](https://github.com/yext/search-headless/releases/tag/v2.0.0) and [documentation](https://github.com/yext/search-headless/blob/main/docs/search-headless.md) of search-headless
- `SearchHeadlessProvider` now takes in a `SearchHeadless` instance instead of a `SearchConfig` object. `SearchHeadlessProvider` will also no longer set vertical key, session tracking, and session id for the `SearchHeadless` instance. Users will need to create and initialize a Headless instance themselves. For more context, this change is made to prevent potential memory leaks, per Redux's recommendation that redux store (i.e. `SearchHeadless` instance) should not be instantiated within a render function. (#156)
- All exports marked as `@deprecated` in previous publish as part of the rebranding process, as well as `subscribeToStateUpdates`, is now removed in V2 (#153  )
  - for more details, the deprecated identifiers are listed in [v1.3 release notes](https://github.com/yext/search-headless-react/releases/tag/v1.3.0)

### CODE REVIEW

**Comment by yen-tt** [comment]
will update headless-react and headless version to 2.0.0 once headless and core version v2 is released.

**Comment by oshi97** [comment]
lowercase v in V1.3

**Comment by oshi97** [comment]
I feel like `may be changed or removed` is a little vague. We know what things have been changed and removed right?

**Comment by yen-tt** [comment]
> Maybe a tiny bit of background on why we changed the provider to be passthrough would be good. I'd probably say something about memory leaks, letting the user choose how to memoize, it's the recommendation for redux stores in general, and "this logic doesn't belong in headless-react" or something

updated description!

**Review by oshi97 — APPROVED** [review]

**Comment by nmanu1** [comment]
> All exports marked as @deprecated in previous publish as part of the rebranding process, as well as subscribeToStateUpdates, is now removed in V2 (#216 )

PR number is from the future 👽

**Review by oshi97 — APPROVED** [review]

**Comment by nmanu1** [comment]
Do we want PR numbers for the first bullet?

**Comment by yen-tt** [comment]
> Do we want PR numbers for the first bullet?

there isn't really one, I can tag the current pr since I bump the version here, but there's no manual code changes for that bullet

**Review by nmanu1 — APPROVED** [review]
> there isn't really one, I can tag the current pr since I bump the version here, but there's no manual code changes for that bullet

nvm then, lgtm!

**Pull request merged**
